-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying NOT NULL UNIQUE,
  nom character varying,
  restaurant_favori_id uuid,
  adresse_default text,
  latitude_default numeric,
  longitude_default numeric,
  nombre_commandes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_order_at timestamp with time zone,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_restaurant_favori_id_fkey FOREIGN KEY (restaurant_favori_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.commandes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_commande character varying NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  sous_total integer NOT NULL CHECK (sous_total >= 0),
  frais_livraison integer DEFAULT 0 CHECK (frais_livraison >= 0),
  total integer NOT NULL CHECK (total >= 0),
  mode character varying NOT NULL CHECK (mode::text = ANY (ARRAY['sur_place'::character varying, 'emporter'::character varying, 'livraison'::character varying]::text[])),
  adresse_livraison text,
  latitude_livraison numeric,
  longitude_livraison numeric,
  distance_km numeric,
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'confirmee'::character varying, 'preparation'::character varying, 'prete'::character varying, 'en_livraison'::character varying, 'livree'::character varying, 'terminee'::character varying, 'annulee'::character varying]::text[])),
  paiement_mode character varying CHECK (paiement_mode::text = ANY (ARRAY['maintenant'::character varying, 'fin_repas'::character varying, 'recuperation'::character varying, 'livraison'::character varying]::text[])),
  paiement_statut character varying DEFAULT 'en_attente'::character varying CHECK (paiement_statut::text = ANY (ARRAY['en_attente'::character varying, 'paye'::character varying, 'echoue'::character varying, 'rembourse'::character varying]::text[])),
  paiement_methode character varying CHECK (paiement_methode::text = ANY (ARRAY['orange_money'::character varying, 'wave'::character varying, 'cash'::character varying, 'carte'::character varying]::text[])),
  livreur_nom character varying,
  livreur_phone character varying,
  note_client text,
  note_restaurant text,
  created_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  prepared_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  estimated_time timestamp with time zone,
  assigned_at timestamp with time zone,
  accepted_by_delivery_at timestamp with time zone,
  validation_code character varying DEFAULT NULL::character varying,
  CONSTRAINT commandes_pkey PRIMARY KEY (id),
  CONSTRAINT commandes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT commandes_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.delivery_stats (
  id bigint NOT NULL DEFAULT nextval('delivery_stats_id_seq'::regclass),
  delivery_user_id bigint NOT NULL,
  date_record date NOT NULL,
  total_deliveries integer DEFAULT 0,
  total_earnings bigint DEFAULT 0,
  average_delivery_time integer DEFAULT 0,
  total_distance numeric DEFAULT 0,
  rating_average numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_stats_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_stats_delivery_user_id_fkey FOREIGN KEY (delivery_user_id) REFERENCES public.delivery_users(id)
);
CREATE TABLE public.delivery_users (
  id bigint NOT NULL DEFAULT nextval('delivery_users_id_seq'::regclass),
  telephone character varying NOT NULL UNIQUE,
  nom character varying NOT NULL,
  code_acces character varying NOT NULL,
  status character varying DEFAULT 'actif'::character varying CHECK (status::text = ANY (ARRAY['actif'::character varying, 'inactif'::character varying, 'suspendu'::character varying]::text[])),
  is_online boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  total_deliveries integer DEFAULT 0,
  total_earnings bigint DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  restaurant_id uuid,
  latitude numeric,
  longitude numeric,
  coordinates_updated_at timestamp with time zone,
  accuracy numeric,
  CONSTRAINT delivery_users_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_users_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.logs_webhook (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying,
  message_in text,
  message_out text,
  state_before character varying,
  state_after character varying,
  error text,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT logs_webhook_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menus (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  nom_plat character varying NOT NULL,
  description text,
  prix integer NOT NULL CHECK (prix > 0),
  categorie character varying DEFAULT 'plat'::character varying CHECK (categorie::text = ANY (ARRAY['entree'::character varying, 'plat'::character varying, 'dessert'::character varying, 'boisson'::character varying, 'accompagnement'::character varying]::text[])),
  disponible boolean DEFAULT true,
  photo_url text,
  ordre_affichage integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menus_pkey PRIMARY KEY (id),
  CONSTRAINT menus_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_analytics (
  id bigint NOT NULL DEFAULT nextval('restaurant_analytics_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  date_record date NOT NULL,
  total_orders integer DEFAULT 0,
  total_revenue bigint DEFAULT 0,
  average_order_value integer DEFAULT 0,
  new_customers integer DEFAULT 0,
  peak_hour integer,
  most_popular_item character varying,
  delivery_orders integer DEFAULT 0,
  takeaway_orders integer DEFAULT 0,
  dine_in_orders integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_analytics_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_status_logs (
  id bigint NOT NULL DEFAULT nextval('restaurant_status_logs_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  old_status character varying,
  new_status character varying NOT NULL,
  reason character varying,
  changed_by_user_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_status_logs_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_status_logs_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES public.restaurant_users(id),
  CONSTRAINT restaurant_status_logs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_users (
  id bigint NOT NULL DEFAULT nextval('restaurant_users_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  nom character varying NOT NULL,
  role character varying DEFAULT 'admin'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'manager'::character varying, 'staff'::character varying]::text[])),
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_users_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_users_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nom character varying NOT NULL,
  adresse text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  phone_whatsapp character varying NOT NULL UNIQUE,
  tarif_km integer DEFAULT 3000,
  seuil_gratuite integer DEFAULT 100000,
  minimum_livraison integer DEFAULT 25000,
  rayon_livraison_km integer DEFAULT 10,
  horaires jsonb DEFAULT '{"jeudi": {"fermeture": "22:00", "ouverture": "11:00"}, "lundi": {"fermeture": "22:00", "ouverture": "11:00"}, "mardi": {"fermeture": "22:00", "ouverture": "11:00"}, "samedi": {"fermeture": "23:00", "ouverture": "12:00"}, "dimanche": {"fermeture": "22:00", "ouverture": "12:00"}, "mercredi": {"fermeture": "22:00", "ouverture": "11:00"}, "vendredi": {"fermeture": "23:00", "ouverture": "11:00"}}'::jsonb,
  statut character varying DEFAULT 'ouvert'::character varying CHECK (statut::text = ANY (ARRAY['ouvert'::character varying, 'ferme'::character varying, 'temporairement_ferme'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying,
  telephone character varying,
  description text,
  logo_url character varying,
  banner_url character varying,
  delivery_fee integer DEFAULT 0,
  min_order_amount integer DEFAULT 0,
  max_delivery_distance numeric DEFAULT 10.0,
  preparation_time integer DEFAULT 30,
  is_featured boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  total_orders integer DEFAULT 0,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying NOT NULL,
  state character varying NOT NULL DEFAULT 'INITIAL'::character varying,
  context jsonb DEFAULT '{}'::jsonb,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:30:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_sessions (
  id bigint NOT NULL DEFAULT nextval('user_sessions_id_seq'::regclass),
  user_id bigint NOT NULL,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['restaurant'::character varying, 'delivery'::character varying]::text[])),
  session_token character varying NOT NULL,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);