-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  action character varying NOT NULL,
  resource_type character varying NOT NULL,
  resource_id uuid,
  changes jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  severity character varying DEFAULT 'info'::character varying CHECK (severity::text = ANY (ARRAY['info'::character varying, 'warning'::character varying, 'critical'::character varying]::text[])),
  CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.super_admins(id)
);
CREATE TABLE public.archive_commandes (
  id uuid NOT NULL,
  numero_commande character varying NOT NULL,
  client_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  items jsonb,
  sous_total integer,
  frais_livraison integer,
  total integer,
  mode character varying,
  adresse_livraison text,
  latitude_livraison numeric,
  longitude_livraison numeric,
  distance_km numeric,
  statut character varying,
  paiement_mode character varying,
  paiement_statut character varying,
  paiement_methode character varying,
  paiement_id character varying,
  livreur_id uuid,
  notes text,
  temps_preparation integer,
  created_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  prepared_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_commandes_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_delivery_users (
  id uuid NOT NULL,
  restaurant_id uuid,
  telephone character varying,
  password character varying,
  nom character varying,
  prenom character varying,
  type_vehicule character varying,
  numero_vehicule character varying,
  is_active boolean,
  is_available boolean,
  current_location jsonb,
  total_deliveries integer,
  rating numeric,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  last_seen timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_delivery_users_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_menus (
  id uuid NOT NULL,
  restaurant_id uuid,
  categorie character varying,
  nom character varying,
  description text,
  prix integer,
  prix_promo integer,
  image_url text,
  is_available boolean,
  is_active boolean,
  ordre integer,
  options jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_menus_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_analytics (
  id uuid NOT NULL,
  restaurant_id uuid,
  date date,
  total_orders integer,
  total_revenue numeric,
  average_order_value numeric,
  new_customers integer,
  returning_customers integer,
  cancelled_orders integer,
  average_preparation_time integer,
  average_delivery_time integer,
  top_dishes jsonb,
  peak_hours jsonb,
  created_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_analytics_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_delivery_config (
  id uuid NOT NULL,
  restaurant_id uuid,
  zone_name character varying,
  coordinates ARRAY,
  delivery_fee integer,
  min_order_amount integer,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_delivery_config_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_payment_config (
  id uuid NOT NULL,
  restaurant_id uuid,
  provider_name character varying,
  is_active boolean,
  api_url text,
  license_key text,
  website_id character varying,
  callback_url text,
  telephone_marchand character varying,
  green_api_instance_id character varying,
  green_api_token text,
  green_api_base_url text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_payment_config_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_payments (
  id uuid NOT NULL,
  restaurant_id uuid,
  commande_id uuid,
  payment_id character varying,
  status character varying,
  amount numeric,
  client_phone character varying,
  message text,
  payment_url text,
  raw_json jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  processed_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_payments_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_subscriptions (
  id uuid NOT NULL,
  restaurant_id uuid,
  plan_name character varying,
  price numeric,
  billing_cycle character varying,
  features jsonb,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  status character varying,
  auto_renew boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_subscriptions_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurant_users (
  id uuid NOT NULL,
  restaurant_id uuid,
  telephone character varying,
  password character varying,
  role character varying,
  nom character varying,
  email character varying,
  is_active boolean,
  last_login timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT archive_restaurant_users_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.archive_restaurants (
  id uuid NOT NULL,
  nom character varying NOT NULL,
  adresse text,
  ville character varying,
  quartier character varying,
  telephone character varying,
  phone_whatsapp character varying,
  email character varying,
  latitude numeric,
  longitude numeric,
  logo_url text,
  banner_url text,
  description text,
  cuisine_types ARRAY,
  heures_ouverture jsonb,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  status character varying,
  is_active boolean,
  can_delivery boolean,
  delivery_fee integer,
  delivery_min_amount integer,
  delivery_max_distance_km numeric,
  min_preparation_time integer,
  max_preparation_time integer,
  currency character varying,
  zone_livraison ARRAY,
  deleted_at timestamp with time zone,
  archived_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_by uuid,
  archive_reason text,
  CONSTRAINT archive_restaurants_pkey PRIMARY KEY (id, archived_at)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying NOT NULL UNIQUE,
  nom character varying,
  restaurant_favori_id uuid,
  adresse_default text,
  latitude_default numeric,
  longitude_default numeric,
  nombre_commandes integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_order_at timestamp with time zone,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_restaurant_favori_id_fkey FOREIGN KEY (restaurant_favori_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.commandes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  numero_commande character varying NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  sous_total integer NOT NULL CHECK (sous_total >= 0),
  frais_livraison integer DEFAULT 0 CHECK (frais_livraison >= 0),
  total integer NOT NULL CHECK (total >= 0),
  mode character varying NOT NULL CHECK (mode::text = ANY (ARRAY['sur_place'::character varying, 'emporter'::character varying, 'livraison'::character varying]::text[])),
  adresse_livraison text,
  latitude_livraison numeric,
  longitude_livraison numeric,
  distance_km numeric,
  statut character varying DEFAULT 'en_attente'::character varying CHECK (statut::text = ANY (ARRAY['en_attente'::character varying, 'confirmee'::character varying, 'preparation'::character varying, 'prete'::character varying, 'en_livraison'::character varying, 'livree'::character varying, 'terminee'::character varying, 'annulee'::character varying]::text[])),
  paiement_mode character varying CHECK (paiement_mode::text = ANY (ARRAY['maintenant'::character varying, 'fin_repas'::character varying, 'recuperation'::character varying, 'livraison'::character varying]::text[])),
  paiement_statut character varying DEFAULT 'en_attente'::character varying CHECK (paiement_statut::text = ANY (ARRAY['en_attente'::character varying, 'paye'::character varying, 'echoue'::character varying, 'rembourse'::character varying]::text[])),
  paiement_methode character varying CHECK (paiement_methode::text = ANY (ARRAY['orange_money'::character varying, 'wave'::character varying, 'cash'::character varying, 'carte'::character varying]::text[])),
  livreur_nom character varying,
  livreur_phone character varying,
  note_client text,
  note_restaurant text,
  created_at timestamp with time zone DEFAULT now(),
  confirmed_at timestamp with time zone,
  prepared_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  estimated_time timestamp with time zone,
  assigned_at timestamp with time zone,
  accepted_by_delivery_at timestamp with time zone,
  validation_code character varying DEFAULT NULL::character varying,
  versement_otp_code character varying,
  versement_otp_generated_at timestamp with time zone,
  versement_otp_validated_at timestamp with time zone,
  versement_otp_attempts integer DEFAULT 0,
  versement_confirmed boolean DEFAULT false,
  CONSTRAINT commandes_pkey PRIMARY KEY (id),
  CONSTRAINT commandes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT commandes_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.delivery_stats (
  id bigint NOT NULL DEFAULT nextval('delivery_stats_id_seq'::regclass),
  delivery_user_id bigint NOT NULL,
  date_record date NOT NULL,
  total_deliveries integer DEFAULT 0,
  total_earnings bigint DEFAULT 0,
  average_delivery_time integer DEFAULT 0,
  total_distance numeric DEFAULT 0,
  rating_average numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delivery_stats_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_stats_delivery_user_id_fkey FOREIGN KEY (delivery_user_id) REFERENCES public.delivery_users(id)
);
CREATE TABLE public.delivery_users (
  id bigint NOT NULL DEFAULT nextval('delivery_users_id_seq'::regclass),
  telephone character varying NOT NULL UNIQUE,
  nom character varying NOT NULL,
  code_acces character varying NOT NULL,
  status character varying DEFAULT 'actif'::character varying CHECK (status::text = ANY (ARRAY['actif'::character varying, 'inactif'::character varying, 'suspendu'::character varying]::text[])),
  is_online boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  total_deliveries integer DEFAULT 0,
  total_earnings bigint DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  restaurant_id uuid,
  latitude numeric,
  longitude numeric,
  coordinates_updated_at timestamp with time zone,
  accuracy numeric,
  is_blocked boolean NOT NULL DEFAULT false,
  CONSTRAINT delivery_users_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_users_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  invoice_number character varying NOT NULL UNIQUE,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'GNF'::character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  due_date date NOT NULL,
  paid_at timestamp with time zone,
  payment_method character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.restaurant_subscriptions(id)
);
CREATE TABLE public.logs_webhook (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying,
  message_in text,
  message_out text,
  state_before character varying,
  state_after character varying,
  error text,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT logs_webhook_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menus (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  nom_plat character varying NOT NULL,
  description text,
  prix integer NOT NULL CHECK (prix > 0),
  categorie character varying DEFAULT 'plat'::character varying CHECK (categorie::text = ANY (ARRAY['entree'::character varying::text, 'plat'::character varying::text, 'dessert'::character varying::text, 'boisson'::character varying::text, 'accompagnement'::character varying::text, 'pizza'::character varying::text, 'burger'::character varying::text, 'sandwich'::character varying::text, 'taco'::character varying::text, 'pates'::character varying::text, 'salade'::character varying::text, 'assiette'::character varying::text, 'naan'::character varying::text])),
  disponible boolean DEFAULT true,
  photo_url text,
  ordre_affichage integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menus_pkey PRIMARY KEY (id),
  CONSTRAINT menus_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_analytics (
  id bigint NOT NULL DEFAULT nextval('restaurant_analytics_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  date_record date NOT NULL,
  total_orders integer DEFAULT 0,
  total_revenue bigint DEFAULT 0,
  average_order_value integer DEFAULT 0,
  new_customers integer DEFAULT 0,
  peak_hour integer,
  most_popular_item character varying,
  delivery_orders integer DEFAULT 0,
  takeaway_orders integer DEFAULT 0,
  dine_in_orders integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_analytics_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid,
  category_key character varying NOT NULL,
  category_name character varying NOT NULL,
  emoji character varying NOT NULL,
  ordre integer NOT NULL DEFAULT 999,
  active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT restaurant_categories_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_categories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_delivery_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL UNIQUE,
  delivery_type character varying NOT NULL CHECK (delivery_type::text = ANY (ARRAY['fixed'::character varying, 'distance_based'::character varying]::text[])),
  fixed_amount integer DEFAULT 0,
  price_per_km integer DEFAULT 0,
  round_up_distance boolean DEFAULT true,
  free_delivery_threshold integer DEFAULT 0,
  max_delivery_radius_km numeric DEFAULT 10.00,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_delivery_config_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_delivery_config_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_payment_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  provider_name character varying NOT NULL DEFAULT 'lengopay'::character varying,
  is_active boolean DEFAULT false,
  api_url character varying DEFAULT 'https://sandbox.lengopay.com/api/v1/payments'::character varying,
  license_key text NOT NULL,
  website_id character varying NOT NULL,
  callback_url character varying NOT NULL,
  green_api_instance_id character varying,
  green_api_token text,
  green_api_base_url character varying DEFAULT 'https://7105.api.greenapi.com'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  telephone_marchand character varying,
  CONSTRAINT restaurant_payment_config_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_payment_config_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  commande_id uuid,
  payment_id character varying NOT NULL,
  status character varying DEFAULT 'PENDING'::character varying CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying]::text[])),
  amount numeric NOT NULL,
  client_phone character varying NOT NULL,
  message text,
  payment_url text,
  raw_json jsonb,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  client_notified_at timestamp with time zone,
  CONSTRAINT restaurant_payments_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_payments_commande_id_fkey FOREIGN KEY (commande_id) REFERENCES public.commandes(id),
  CONSTRAINT restaurant_payments_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_status_logs (
  id bigint NOT NULL DEFAULT nextval('restaurant_status_logs_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  old_status character varying,
  new_status character varying NOT NULL,
  reason character varying,
  changed_by_user_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_status_logs_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_status_logs_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES public.restaurant_users(id),
  CONSTRAINT restaurant_status_logs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurant_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'trial'::character varying, 'suspended'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  next_billing_date timestamp with time zone,
  payment_method jsonb,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_subscriptions_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT restaurant_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.restaurant_users (
  id bigint NOT NULL DEFAULT nextval('restaurant_users_id_seq'::regclass),
  restaurant_id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  nom character varying NOT NULL,
  role character varying DEFAULT 'admin'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'manager'::character varying, 'staff'::character varying]::text[])),
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_users_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_users_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nom character varying NOT NULL,
  adresse text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  phone_whatsapp character varying NOT NULL UNIQUE,
  tarif_km integer DEFAULT 3000,
  seuil_gratuite integer DEFAULT 100000,
  minimum_livraison integer DEFAULT 25000,
  rayon_livraison_km integer DEFAULT 10,
  horaires jsonb DEFAULT '{"jeudi": {"fermeture": "22:00", "ouverture": "11:00"}, "lundi": {"fermeture": "22:00", "ouverture": "11:00"}, "mardi": {"fermeture": "22:00", "ouverture": "11:00"}, "samedi": {"fermeture": "23:00", "ouverture": "12:00"}, "dimanche": {"fermeture": "22:00", "ouverture": "12:00"}, "mercredi": {"fermeture": "22:00", "ouverture": "11:00"}, "vendredi": {"fermeture": "23:00", "ouverture": "11:00"}}'::jsonb,
  statut character varying DEFAULT 'ouvert'::character varying CHECK (statut::text = ANY (ARRAY['ouvert'::character varying, 'ferme'::character varying, 'temporairement_ferme'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying,
  telephone character varying,
  description text,
  logo_url character varying,
  banner_url character varying,
  delivery_fee integer DEFAULT 0,
  min_order_amount integer DEFAULT 0,
  max_delivery_distance numeric DEFAULT 10.0,
  preparation_time integer DEFAULT 30,
  is_featured boolean DEFAULT false,
  rating numeric DEFAULT 0.00,
  total_orders integer DEFAULT 0,
  currency character varying DEFAULT 'GNF'::character varying CHECK (currency::text = ANY (ARRAY['GNF'::character varying, 'XOF'::character varying, 'EUR'::character varying, 'USD'::character varying]::text[])),
  password character varying,
  allow_dine_in boolean DEFAULT true,
  allow_takeaway boolean DEFAULT true,
  allow_delivery boolean DEFAULT true,
  allow_pay_now boolean DEFAULT false,
  allow_pay_later boolean DEFAULT true,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'suspended'::character varying, 'pending'::character varying, 'banned'::character varying, 'deleted'::character varying]::text[])),
  owner_name character varying,
  last_activity_at timestamp with time zone,
  suspension_reason text,
  deleted_at timestamp with time zone,
  first_login boolean DEFAULT true,
  is_blocked boolean DEFAULT false,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_whatsapp character varying NOT NULL,
  state character varying NOT NULL DEFAULT 'INITIAL'::character varying,
  context jsonb DEFAULT '{}'::jsonb,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:30:00'::interval),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  price numeric NOT NULL,
  currency character varying DEFAULT 'GNF'::character varying,
  features jsonb NOT NULL DEFAULT '{}'::jsonb,
  billing_cycle character varying NOT NULL CHECK (billing_cycle::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying]::text[])),
  max_orders integer,
  max_drivers integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.super_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['super_admin'::character varying, 'admin'::character varying, 'support'::character varying]::text[])),
  permissions jsonb DEFAULT '[]'::jsonb,
  mfa_secret character varying,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT super_admins_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  key character varying NOT NULL,
  value jsonb NOT NULL,
  description text,
  category character varying DEFAULT 'general'::character varying,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (key),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.super_admins(id)
);
CREATE TABLE public.user_sessions (
  id bigint NOT NULL DEFAULT nextval('user_sessions_id_seq'::regclass),
  user_id bigint NOT NULL,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['restaurant'::character varying, 'delivery'::character varying]::text[])),
  session_token character varying NOT NULL,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);