-- ========================================================================
-- INSERTION INGRÉDIENTS SUPPLÉMENTAIRES TORTILLAS - TOUS LES PRODUITS (COMPLET)
-- DATE: 2025-10-21
-- ========================================================================
-- Restaurant: Plan B Melun (id=22)
-- Objectif : Ajouter les 22 ingrédients supplémentaires pour tous les 12 produits TORTILLAS
-- Total: 264 options (22 ingrédients × 12 produits)
-- ========================================================================
-- Généré automatiquement par generate_tortillas_ingredients.py
-- ========================================================================

BEGIN;

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA CURRY (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA CURRY' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA TANDOORI (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TANDOORI' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA MIX TENDERS (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA MIX TENDERS' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA BOURSIN (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOURSIN' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA VACHE QUI RIT (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA VACHE QUI RIT' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA DINA (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA DINA' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA BOX MASTER (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA BOX MASTER' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA SPECIAL (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA SPECIAL' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA RUSTIK (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA RUSTIK' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA TRIPLE X (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA TRIPLE X' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA B SIX (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA B SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- INGRÉDIENTS SUPPLÉMENTAIRES POUR TORTILLA C SIX (22 options)
-- ========================================================================
INSERT INTO france_product_options (product_id, option_group, option_name, composition, price_modifier, icon, display_order, is_active) VALUES
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oignons rouges', 'Oignons rouges supplémentaires', 1.00, '🧅', 1, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'olives', 'Olives supplémentaires', 1.00, '🫒', 2, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poivrons', 'Poivrons supplémentaires', 1.00, '🫑', 3, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'salade', 'Salade supplémentaire', 1.00, '🥗', 4, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tomates', 'Tomates supplémentaires', 1.00, '🍅', 5, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'bacon', 'Bacon supplémentaire', 1.50, '🥓', 6, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'crevettes', 'Crevettes supplémentaires', 1.50, '🦐', 7, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'escalope', 'Escalope supplémentaire', 1.50, '🍗', 8, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'oeuf', 'Œuf supplémentaire', 1.50, '🥚', 9, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet', 'Poulet supplémentaire', 1.50, '🍗', 10, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet curry', 'Poulet curry supplémentaire', 1.50, '🍛', 11, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'poulet tandoori', 'Poulet tandoori supplémentaire', 1.50, '🌶️', 12, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'saumon', 'Saumon supplémentaire', 1.50, '🐟', 13, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 120gr', 'Steak 120gr supplémentaire', 2.00, '🥩', 14, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'steak 90gr', 'Steak 90gr supplémentaire', 2.00, '🥩', 15, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'tenders', 'Tenders supplémentaires', 1.50, '🍗', 16, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'boursin', 'Boursin supplémentaire', 1.00, '🧀', 17, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'cheddar', 'Cheddar supplémentaire', 1.00, '🧀', 18, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'chèvre', 'Chèvre supplémentaire', 1.00, '🐐', 19, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'mozzarella', 'Mozzarella supplémentaire', 1.00, '🧀', 20, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'raclette', 'Raclette supplémentaire', 1.00, '🧀', 21, true),
((SELECT id FROM france_products WHERE name = 'TORTILLA C SIX' AND category_id = (SELECT id FROM france_menu_categories WHERE slug = 'tortillas' AND restaurant_id = 22)), 'Ingredients Supplementaires', 'reblochon', 'Reblochon supplémentaire', 1.00, '🧀', 22, true);

-- ========================================================================
-- VÉRIFICATIONS
-- ========================================================================

-- Vérifier le nombre d'ingrédients par produit (doit être 22 partout)
SELECT
  p.name as produit,
  COUNT(*) as nb_ingredients
FROM france_product_options po
JOIN france_products p ON p.id = po.product_id
JOIN france_menu_categories c ON c.id = p.category_id
WHERE p.restaurant_id = 22
  AND c.slug = 'tortillas'
  AND po.option_group = 'Ingredients Supplementaires'
GROUP BY p.name, p.display_order
ORDER BY p.display_order;

-- Vérifier le total (doit être 264)
SELECT COUNT(*) as total_ingredients, '264 attendu' AS verification
FROM france_product_options po
JOIN france_products p ON p.id = po.product_id
JOIN france_menu_categories c ON c.id = p.category_id
WHERE p.restaurant_id = 22
  AND c.slug = 'tortillas'
  AND po.option_group = 'Ingredients Supplementaires';

COMMIT;

-- ========================================================================
-- RÉSULTAT ATTENDU :
-- ========================================================================
-- 264 options d'ingrédients supplémentaires ajoutées (22 × 12 produits)
--
-- Total options TORTILLAS après ce script :
-- - Choix Pain: 24 options (2 × 12)
-- - Sauces: 156 options (13 × 12)
-- - Ingrédients Supplémentaires: 264 options (22 × 12)
-- TOTAL: 444 options
-- ========================================================================
